encoder_parameters:
  embed_dim: 200
  hidden_dim: 200
  num_layers: 200
  dropout_rate: 0
decoder_parameters:
  hidden_dime: 200
  num_layers: 200
  dropout_rate: 0
optimizer: "Adam"
learning_rate: 0.01
batch_size: 200
checkpoints_per_epoch: 6
load_model_path: ""
half_lr: True
early_stopping: False