dimensions:
  hidden1: 300
  hidden2: 500
  embed_dim: 200
activation_function: "relu"
optimizer: "Adam"
learning_rate: 0.001
use_custom_linear_layer: False
batch_size: 200
checkpoints_per_epoch: 0
load_model_path: ""
