dimensions:
  hidden1: 300
  hidden2: 500
  embed_dim: 200
activation_function: "relu"
optimizer: "Adam"
learning_rate: 0.001
use_custom_linear_layer: False
batch_size: 200
checkpoints_per_epoch: 5
load_model_path: ""
half_lr: False
window_size: 3
dropout_rate: 0.3
early_stopping: False
