dimensions:
  hidden1: 300
  hidden2: 500
  embed_dim: 200
window_size: 2
activation_function: "relu"
optimizer: "Adam"
learning_rate: 0.001
use_custom_linear_layer: False
batch_size: 200
checkpoints_per_epoch: 200
load_model_path: "../eval/checkpoints/10-06-2024/21_56_44/MODEL.pth"
half_lr: True
